site_name: SciCD Documentation
theme: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Configuration: user-guide/configuration.md
      - Build Process: user-guide/build.md
      - CLI & Overrides: user-guide/cli.md
      - Task Development: user-guide/tasks.md
  - Reference:
      - Architecture: reference/architecture.md
  - Roadmap: roadmap.md
  - Developer Guide:
      - Testing: developer/testing.md
