
default:
  tags:
  - $RUNNER
  image: python:3.10
  before_script:
  - apt-get update && apt-get install -y rclone
  - pip install -e .
  - ./script/install_deps.sh

variables:
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_MEMORY_REQUEST: 4Gi
  PYTHONUNBUFFERED: '1'

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
    when: never
  - when: always

include:
- local: ci/pipeline.yml

stages:
- __pull__
- Independent
- PubsubExample
- ScriptTest
- Hello
- IndependentStill
