
PubsubExample:dispatch:
  needs:
  - job: PubsubExample:prepare
    optional: true
  parallel: 10
  script:
  - scicd dispatch_module PubsubExample --method=queue
  stage: dispatch

PubsubExample:prepare:
  script:
  - scicd prepare_module PubsubExample --method=queue
  stage: prepare

default:
  before_script:
  - apt-get update && apt-get install -y rclone
  - ./script/install_deps.sh
  image: python:3.10
  tags:
  - $RUNNER

stages:
- prepare
- dispatch

variables:
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_MEMORY_REQUEST: 4Gi
  PYTHONUNBUFFERED: '1'

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
    when: never
  - when: always
