
ScriptTest:subject=SubA:
  script:
  - scicd dispatch_module ScriptTest --method=matrix
  stage: dispatch
  variables:
    SCICD_INPUT: '{"subject": "SubA"}'

ScriptTest:subject=SubB:
  script:
  - scicd dispatch_module ScriptTest --method=matrix
  stage: dispatch
  variables:
    SCICD_INPUT: '{"subject": "SubB"}'

ScriptTest:subject=SubC:
  script:
  - scicd dispatch_module ScriptTest --method=matrix
  stage: dispatch
  variables:
    SCICD_INPUT: '{"subject": "SubC"}'

default:
  before_script:
  - apt-get update && apt-get install -y rclone
  - ./script/install_deps.sh
  image: python:3.10
  tags:
  - $RUNNER

stages:
- dispatch

variables:
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_MEMORY_REQUEST: 4Gi
  PYTHONUNBUFFERED: '1'

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
    when: never
  - when: always
